# Generated by Django 5.1.1 on 2024-10-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=25, verbose_name='Nombre del tipo de producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('descripcion_producto', models.TextField(verbose_name='Descripción del producto')),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('stock_producto', models.IntegerField(verbose_name='Stock del producto')),
                ('imagen_uno', models.ImageField(upload_to='productos/', verbose_name='Primera imagen')),
                ('imagen_dos', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Segunda imagen')),
                ('imagen_tres', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Tercera imagen')),
                ('imagen_cuatro', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Cuarta imagen')),
                ('tipo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoproducto', verbose_name='Tipo de producto')),
            ],
        ),
    ]
