# Generated by Django 5.1.1 on 2024-10-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_capacidad_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='socket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sockets que contiene el componente'),
        ),
    ]
