# Generated by Django 5.1.1 on 2024-11-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_producto_frecuencia_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_producto',
            field=models.IntegerField(default=0, verbose_name='Stock del producto'),
        ),
    ]
