# Generated by Django 5.1.1 on 2024-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
