# Generated by Django 5.1.1 on 2024-12-10 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_post_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_cuatro',
            field=models.ImageField(blank=True, default='productos/default.jpg', null=True, upload_to='productos/', verbose_name='Cuarta imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_dos',
            field=models.ImageField(blank=True, default='productos/default.jpg', null=True, upload_to='productos/', verbose_name='Segunda imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_tres',
            field=models.ImageField(blank=True, default='productos/default.jpg', null=True, upload_to='productos/', verbose_name='Tercera imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default='productos/default.jpg', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoproducto', verbose_name='Tipo de producto'),
        ),
    ]
