-- Tabla auth_group
CREATE TABLE auth_group (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL UNIQUE
);

-- Tabla auth_permission
CREATE TABLE auth_permission (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    content_type_id NUMBER(10, 0) NOT NULL,
    codename VARCHAR2(100) NOT NULL,
    UNIQUE (content_type_id, codename)
);

-- Tabla django_content_type
CREATE TABLE django_content_type (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label VARCHAR2(100) NOT NULL,
    model VARCHAR2(100) NOT NULL,
    UNIQUE (app_label, model)
);

-- Relaciones entre las tablas auth_permission y django_content_type
ALTER TABLE auth_permission 
ADD CONSTRAINT fk_permission_content_type
FOREIGN KEY (content_type_id)
REFERENCES django_content_type (id)
ON DELETE CASCADE;

-- Tabla Rol
CREATE TABLE rol (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreRol VARCHAR2(25) NOT NULL
);

-- Tabla Usuario
CREATE TABLE usuario (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(128) NOT NULL,
    email VARCHAR2(254) UNIQUE,
    rol_id NUMBER(10, 0),
    foto_perfil VARCHAR2(255) DEFAULT 'foto_perfil/default.jpg',
    codigo_recuperacion VARCHAR2(6),
    FOREIGN KEY (rol_id) REFERENCES rol(id) ON DELETE SET NULL
);

-- Tabla TipoProducto
CREATE TABLE tipo_producto (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo VARCHAR2(25) NOT NULL
);

-- Tabla Producto
CREATE TABLE producto (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR2(255) NOT NULL,
    descripcion_producto CLOB,
    precio_producto NUMBER(10, 2) DEFAULT 0,
    stock_producto NUMBER(10, 0) DEFAULT 0,
    imagen_uno VARCHAR2(255),
    imagen_dos VARCHAR2(255),
    imagen_tres VARCHAR2(255),
    imagen_cuatro VARCHAR2(255),
    tipo_producto_id NUMBER(10, 0),
    activo NUMBER(1) DEFAULT 1,
    marca VARCHAR2(50),
    modelo VARCHAR2(100),
    socket VARCHAR2(100),
    memoria_video NUMBER(10, 0),
    tipo_memoria VARCHAR2(10),
    capacidad_almacenamiento NUMBER(10, 0),
    frecuencia_ram NUMBER(10, 0),
    velocidad_lectura NUMBER(10, 0),
    velocidad_escritura NUMBER(10, 0),
    frecuencia_base NUMBER(5, 2),
    frecuencia_boost NUMBER(5, 2),
    nucleos NUMBER(10, 0),
    hilos NUMBER(10, 0),
    FOREIGN KEY (tipo_producto_id) REFERENCES tipo_producto(id) ON DELETE RESTRICT
);

-- Tabla Post
CREATE TABLE post (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    contenido CLOB,
    autor_id NUMBER(10, 0) NOT NULL,
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (autor_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Tabla Like
CREATE TABLE like (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id NUMBER(10, 0) NOT NULL,
    usuario_id NUMBER(10, 0) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, usuario_id),
    FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Tabla Comentario
CREATE TABLE comentario (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id NUMBER(10, 0) NOT NULL,
    autor_id NUMBER(10, 0) NOT NULL,
    contenido CLOB NOT NULL,
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE,
    FOREIGN KEY (autor_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Tabla Carrito
CREATE TABLE carrito (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER(10, 0) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Tabla ItemCarrito
CREATE TABLE item_carrito (
    id NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_id NUMBER(10, 0) NOT NULL,
    producto_id NUMBER(10, 0) NOT NULL,
    cantidad NUMBER(10, 0) DEFAULT 1,
    FOREIGN KEY (carrito_id) REFERENCES carrito(id) ON DELETE CASCADE,
    FOREIGN KEY (producto_id) REFERENCES producto(id) ON DELETE CASCADE
);
